# Generated by Django 3.1.7 on 2021-04-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
