# Generated by Django 3.1.7 on 2021-04-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210405_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар/заказ', 'verbose_name_plural': 'Товары/заказ'},
        ),
    ]
